version: '3.7'
services:
  app:
    env_file:
      ./.env
    build: ./app
    ports:
      - "8001:80"
    entrypoint:
      - /goapp/app

  db:
    image: mysql:8.0.27
    env_file:
      ./.env
    volumes:
       - "db-data:/var/lib/mysql"
    environment:
      - MYSQL_USER=${TIMER_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=synmodoro
      # Specify the above two passwords in `.env` file.

volumes:
  db-data:
