baseURL = 'http://synmodoro.coppelab.net/'
languageCode = 'ja-jp'
title = 'Synmodoro'

theme = "PaperMod"

[params]
  description = "Synchronize your pomodoro timer with your mates."
  discord = "https://discord.gg/VBbheacPk7"
